name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Environment File
        run: |
          echo "VITE_DEVLOG_AVATAR_URL=${{ secrets.VITE_DEVLOG_AVATAR_URL }}" >> .env
          echo "VITE_DEVLOG_BANNERS=${{ secrets.VITE_DEVLOG_BANNERS }}" >> .env
          echo "VITE_UTTERANCE_REPO=${{ secrets.VITE_UTTERANCE_REPO }}" >> .env

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHORIZATION_TOKEN }}

      - name: Set Docker Buildx Platform
        uses: docker/setup-buildx-action@v3
        with:
          platform: linux/arm64

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest

  deploy:
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker stop ${{ secrets.DOCKER_CONTAINER_NAME }} || true
            docker rm ${{ secrets.DOCKER_CONTAINER_NAME }} || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest
            docker run -d --name ${{ secrets.DOCKER_CONTAINER_NAME }} -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest
